<a href="https://colab.research.google.com/github/aquapirate/worksheet0/blob/main/2408239_NikishaShrestha1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Nikisha Shrestha
# Problem1
# Question1
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[4.93951778e-310 0.00000000e+000]
 [9.03285276e+271 1.19011338e-147]]


In [ ]:
# Question2
import numpy as np
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Question3
import numpy as np
new_array = np.full((2,2), 10, dtype=None)
print(new_array)

[[10 10]
 [10 10]]


In [ ]:
# Question4
import numpy as np
given_array = np.ones((2,2))
print(np.zeros_like(given_array))

[[0. 0.]
 [0. 0.]]


In [ ]:
# Question5
import numpy as np
given_array = np.zeros((2,2))
print(np.ones_like(given_array))

[[1. 1.]
 [1. 1.]]


In [ ]:
# Question6
import numpy as np
new_list = [1,2,3,4]
print(np.array(new_list))

[1 2 3 4]


In [ ]:
# Problem2
# Question1
import numpy as np
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Question2
import numpy as np
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question3
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Question4
import numpy as np
array = np.random.random(30)
print(array)
print(array.mean())

[0.54008229 0.13126951 0.9142191  0.96824145 0.94659708 0.59691413
 0.6738363  0.58735772 0.00716204 0.34660468 0.9604477  0.35632154
 0.80097274 0.22210965 0.97805763 0.71551377 0.83714945 0.79917168
 0.31691646 0.37109202 0.54222647 0.76843656 0.17163236 0.31395484
 0.68045361 0.6980896  0.91241245 0.12605216 0.51753744 0.13064348]
0.5643825301057688


In [ ]:
# Question5
import numpy as np
array = np.random.random((10,10))
print(np.max(array))
print(np.min(array))

0.9921345189219235
0.012885847872288969


In [ ]:
# Question6
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Question7
import numpy as np
array = np.array([1,2,0,0,4,0])
print(np.flip(array))

[0 4 0 0 2 1]


In [ ]:
# Question8
import numpy as np
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Question9
import numpy as np
array = np.full((8,8), 0)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Problem 3
# Question1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x + y)
print(v + w)

[[ 6  8]
 [10 13]]
[20 22]


In [ ]:
# Question2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x - y)
print(v - w)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [ ]:
# Question3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x * 2)
print(y * 2)
print(v * 2)
print(w * 2)

[[ 2  4]
 [ 6 10]]
[[10 12]
 [14 16]]
[18 20]
[22 24]


In [ ]:
# Question4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [ ]:
# Question5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.dot(x,y))
print(np.dot(v,w))


[[19 22]
 [50 58]]
219


In [ ]:
# Question6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.concatenate((x,y), axis=0))
print(np.concatenate((v.reshape(-1,1),w.reshape(-1,1)), axis=1))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
# Question7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
print(np.concatenate(x,v), axis=0)
# we get an error because inorder to concatenate along the rows,
# the number of cloumn must match across the arrays.


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
# Problem4
# Question1
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(np.round(result, decimals=10))

AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)

ABT = np.transpose(AB)
print(ABT)
AT = np.transpose(A)
BT = np.transpose(B)
BTAT = np.dot(BT, AT)
print(BTAT)

[[1. 0.]
 [0. 1.]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
# Question2
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])


In [ ]:
# Question3
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
result = np.dot(A_inv, B)
print(result)
# The numpy.linalg module in Numpy provides a powerful suite of linear algebra
# functions that make it easier to perform operations commonly used in 4
# mathematics,and Machine Learning.

[ 2.  1. -2.]


In [ ]:
# 4.2
import numpy as np
import time

# List and Numpy Array Initialization
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
np_array1 = np.arange(size)
np_array2 = np.arange(size)

# Element-wise Addition
print("Element-wise Addition:")

# Using Python Lists
start_time = time.time()
list_result_add = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_result_add = np_array1 + np_array2
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Element-wise Multiplication
print("\nElement-wise Multiplication:")

# Using Python Lists
start_time = time.time()
list_result_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_result_mul = np_array1 * np_array2
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Dot Product
print("\nDot Product:")

# Using Python Lists
start_time = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_dot_product = np.dot(np_array1, np_array2)
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Matrix Multiplication
print("\nMatrix Multiplication:")
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Using Python Lists
def matrix_mult(mat1, mat2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]
    return result

start_time = time.time()
list_matrix_result = matrix_mult(list_matrix1, list_matrix2)
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_matrix_result = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")


Element-wise Addition:
Python Lists: 0.165211 seconds
NumPy Arrays: 0.030408 seconds

Element-wise Multiplication:
Python Lists: 0.151843 seconds
NumPy Arrays: 0.004307 seconds

Dot Product:
Python Lists: 0.156864 seconds
NumPy Arrays: 0.002005 seconds

Matrix Multiplication:
Python Lists: 207.765707 seconds
NumPy Arrays: 1.278038 seconds
